baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
paginate = 2 


theme = [
"github.com/asteriskdigital/hugo-tags-alpinejs",
"github.com/theNewDynamic/gohugo-theme-ananke"
]
[module]
[[module.imports]]
  path = "github.com/pointyfar/hmd-content"
  disable=false
  [[module.imports.mounts]]
    source="content/looking-glass"
    target="content/posts"

[[module.mounts]]
  source = "themes/theme/layouts"
  target = "assets/layouts"

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "assets"
  target = "assets"

[taxonomies]
tag = "tags"
author = "authors"